### ISSUE TITLE
Cyrillic font support

### ISSUE THREAD

**Issue by kfreiman** [riot/riot.github.io#30]
Russian translations was started #29. At site used font "Proxima Nova" which suports Cyrillic, but in some reason, renders it not correctly. Sans-serif applies instead.

![bb90990be5](https://cloud.githubusercontent.com/assets/2056294/9706172/a9f99fb8-54e6-11e5-8946-7601c20cb1bd.png)

**Comment by cognitom** [comment]
@kfreiman feel free to add a language specific font to `ru` template.

For example, this is a `ja` template:
https://github.com/riot/riot.github.io/blob/master/_layouts/ja.html

You could add `<style>/* override something */</style>` after `<link rel="stylesheet" href="/style.css">` in your `ru.html`.

**Comment by kfreiman** [comment]
Now cyrillic font looks more comfortable:
[cyrillic font](http://joxi.ru/VrwlEOESZgO8mX.png)
it is "Didact Gothic" from google fonts. Latin symbols looks very similar to original, but I don't use the "Proxima Nova" because it is not free.

**Comment by kfreiman** [comment]
@s-melnikov, добро пожаловать!

Im not quite satisfied "Didact Gothic" too. But it is most similar to the original's "Proxima Nova" free font that I have found. I think it needs to be discussed.

1. without changes           ![without changes](http://dl1.joxi.net/drive/0011/1253/722149/151110/5bf052de0f.png)         
2. Didact Gothic             ![Didact Gothic](http://dl1.joxi.net/drive/0011/1253/722149/151110/b4440d503b.png)         
3. @s-melnikovs Open Sans    ![Open Sans](http://dl2.joxi.net/drive/0011/1253/722149/151110/699d0d165a.png)         

@tipiirai, have you "Proxima Nova" with Cyrillic support?

**Comment by s-melnikov** [comment]
Maybe use "Roboto" font?

En/"Proxima Nova"
![003](https://cloud.githubusercontent.com/assets/13319141/11120401/f24c8ea6-8957-11e5-8f8d-b909ed0dab6e.jpg)

En/"Roboto"
![002](https://cloud.githubusercontent.com/assets/13319141/11120408/0ba00702-8958-11e5-8a56-6b12f83b4cb9.jpg)

Ru/"Roboto"
![001](https://cloud.githubusercontent.com/assets/13319141/11120410/12bc1b3e-8958-11e5-8935-c4fb956c9b65.jpg)

```css
@import url(https://fonts.googleapis.com/css?family=Roboto:400,300,400italic,500,500italic,300italic&subset=latin,cyrillic);
html {
  font-family: Roboto, sans-serif;
  font-weight: 300;
}
h1, h2, h3, h4, h5 {
  font-weight: 500;
}
```
